
DROP TABLE IF EXISTS ALFAPENDULAR

DROP TABLE IF EXISTS LOCOMOTIVA

DROP TABLE IF EXISTS BILHETE

DROP TABLE IF EXISTS PAGMBWAY

DROP TABLE IF EXISTS LUGAR

DROP TABLE IF EXISTS COMBOIO

DROP TABLE IF EXISTS AUTOCARRO

DROP TABLE IF EXISTS TRANSPORTE

DROP TABLE IF EXISTS RESERVA

DROP TABLE IF EXISTS VIAGEM

DROP TABLE IF EXISTS ESTACAO

DROP TABLE IF EXISTS LUGARTIPO

DROP TABLE IF EXISTS AUTOCARROTIPO

DROP TABLE IF EXISTS COMBOIOTIPO

DROP TABLE IF EXISTS LOCALIDADE

DROP TABLE IF EXISTS PASSAGEIRO



